
auth.token=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

defaults.org=kaizen-g5
defaults.project=react-native-test

defaults.url=https://sentry.io/
